version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  db:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
    
volumes:
  mongodata: